version: '3'

services:
  db:
    image: mysql:latest
    command: --init-file /data/application/init.sql
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lovify
      MYSQL_USER: cipe
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'